name: Download bond monthly stats
on:
  schedule:
    - cron: '0 22 * * 0'
  push:
    branches: [ "main" ]

jobs:
  deploy:
    permissions: 
      contents:  'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Download bont monthly stats
        run: Rscript R/download_bond_monthly_stats.R
      - name: Commit results
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add Data/*
          git commit -am "Bond stats downloaded on $(date)"
          git push origin main
