name: "Download bond monthly stats"
on:
  schedule:
    - cron: '0 22 * * 0'


permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      # - name: Download a file
      #   run: curl https://gpwcatalyst.pl/pub/CATALYST/statystyki/statystyki_miesieczne/202308_CAT.xls -o Data/statystyki_obligacji_downloaded_2023-10-02.xls

      - name: Download bond monthly stats
        # run: wget -O Data/statystyki_obligacji_downloaded_2023-10-02.xls https://gpwcatalyst.pl/pub/CATALYST/statystyki/statystyki_miesieczne/202308_CAT.xls
        run: Rscript R/download_bond_monthly_stats.R
      - name: Commit results
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add Data/*
          git commit -am "Bond stats update $(date)"
          git push origin main
        # env:
        #   REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        #   username: github-actions
