name: Scrape bond data

on:
  schedule:
    - cron: '0 21 * * 0'
  push:
    branches: main

permissions: write-all

jobs:
  render:
    name: Update bond dates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Scrape the data
        run: Rscript R/scraping_bond_data.R
      - name: Commit results
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add Data/*
          git commit -am "Bond data scraped $(date)"
          git push origin main


