# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Update bond dates

on:
  schedule:
    - cron: '0 23 * * *'

permissions: write-all

jobs:
  render:
    name: Update bond dates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.CREDENTIALS_JSON }}'
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Scrape the data
        run: Rscript R/update_dates.R
      - name: Commit results
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add Data/*
          git commit -am "Bond dates update $(date)"
          git push origin main
        # env:
        #   REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        #   username: github-actions


